### ISSUE TITLE
There are no commands defined in the "eav:media" namespace.

### ISSUE THREAD

**Issue by secaliskan** [magento-hackathon/EAVCleaner#40]
Hi, Ive been disappointed.
readme file no showing composer installation.. even not giving clear information for supported php and magento versions...

Copy paste EAVcleaner under app/code... and what is further commands? Why you dont show exact installation path  step by step? 
we dont run `bin/magento setup:upgrade`, or `bin/magento setup:di:compile` or `bin/magento setup:static-content:deploy` ??
which one we have to use? 
I could not be successfull installing the extension since there's no clear path given for installation.
Weird situation as we know you are experts on magento2

please make clear the installation process. 
looking forward to hearing from you soon.

Savas

**Comment by koentjeh** [comment]
This is not an issue within the module. You can try to install using `composer require hackathon/magento2-eavcleaner`.

Another way to validate if the extension is ready for use is to use `bin/magento list`. If `eav:media` is the only command to not show up you might need to check if the module is enabled. Otherwise it's probably an issue with composer where you can use `composer dumpautoload` to correct the file paths.
